### ISSUE TITLE
Link in Philosophy tree is dead

### ISSUE THREAD

**Issue by elogada** [jhaddix/tbhm#16]
One of the links in the Philosophy folder seems to redirect to the home page instead of the page mentioned straight from the markdown.

```
https://blog.bugcrowd.com/advice-for-writing-a-great-vulnerability-report/
```

**Comment by larssorenson** [comment]
Looks like they reworked the URL slightly and it should point to https://www.bugcrowd.com/blog/advice-for-writing-a-great-vulnerability-report/

**Comment by elogada** [comment]
Sorry for the late reply. Seems to work now.

Closing thread
